require 'rake/clean'

TARGET_DIR = "jashboard_app"
SERVER_ROOT = File.join(File.dirname(__FILE__), "../server")
WEB_ROOT = File.join(File.dirname(__FILE__), "../web")
TARGET_DIR_WEB = "#{TARGET_DIR}/app/web"

def copy_and_replace(src, dest, pattern, replace)
  text = File.read(src) 
  text.gsub!(pattern, replace)
  File.open(dest, "w") { |file| file.write(text) }
end

CLEAN.include(TARGET_DIR)

directory TARGET_DIR
directory TARGET_DIR_WEB

task :init => [:clean, TARGET_DIR]

task :install_server_files => [TARGET_DIR] do
  cp_r "#{SERVER_ROOT}/app", TARGET_DIR
  ["#{SERVER_ROOT}/Gemfile", "#{SERVER_ROOT}/start_server.sh"].each {|f| cp(f, TARGET_DIR)}
  copy_and_replace("#{SERVER_ROOT}/config.ru", "#{TARGET_DIR}/config.ru", /current_environment\s+=\s+'development'/, "current_environment = 'production'")
  mkdir_p "#{TARGET_DIR}/db/production/dashboard"
  mkdir_p "#{TARGET_DIR}/db/production/monitor"
end

task :copy_html_files =>[TARGET_DIR, TARGET_DIR_WEB] do
  cp "#{WEB_ROOT}/index.html", TARGET_DIR_WEB
  cp_r "#{WEB_ROOT}/html", TARGET_DIR_WEB
end

task :copy_img_files => [TARGET_DIR, TARGET_DIR_WEB] do
  cp_r "#{WEB_ROOT}/img", TARGET_DIR_WEB
end

task :copy_lib_files => [TARGET_DIR, TARGET_DIR_WEB] do
  mkdir_p "#{TARGET_DIR_WEB}/lib"
  [
    "#{WEB_ROOT}/lib/jquery.cycle2.min.js",
  ].each {|f| cp(f, "#{TARGET_DIR_WEB}/lib")}
end

task :copy_app_files => [TARGET_DIR, TARGET_DIR_WEB] do
  mkdir_p "#{TARGET_DIR_WEB}/app"
  copy_and_replace("#{WEB_ROOT}/app/configuration.js", "#{TARGET_DIR_WEB}/app/configuration.js", /var\s+JASHBOARD_ENVIRONMENT\s+=\s+'development';/, "var JASHBOARD_ENVIRONMENT = 'production';")
  cp "#{WEB_ROOT}/bower.json", "#{TARGET_DIR_WEB}"
  system 'npm install', {chdir: WEB_ROOT}
  system 'grunt build', {chdir: WEB_ROOT}
  mv "#{WEB_ROOT}/app/jashboard.min.js", "#{TARGET_DIR_WEB}/app"
  mv "#{WEB_ROOT}/app/jashboard.min.css", "#{TARGET_DIR_WEB}/app"
end

task :install_dependencies => [TARGET_DIR, TARGET_DIR_WEB] do
  puts 'installing ruby libraries'
  system 'bundle install --without=test', {chdir: TARGET_DIR}
  puts 'installing javascript libraries'
  system 'bower install -p', {chdir: TARGET_DIR_WEB}
end

multitask :install_web_files => [:copy_html_files, :copy_img_files, :copy_lib_files, :copy_app_files]

desc "install the application in folder: #{File.join(File.dirname(__FILE__), TARGET_DIR)}"
task :install =>[:init, :install_server_files, :install_web_files, :install_dependencies] do
  out = "Jashboard installed in #{TARGET_DIR}."
  delimiter = Array.new(out.length + 2, '-').join()
  puts <<-EOF
 #{delimiter}
| #{out} |
 #{delimiter}
EOF
end
