require 'rake/clean'

TARGET_DIR = "jashboard_app"
SERVER_ROOT = File.join(File.dirname(__FILE__), "../server")
WEB_ROOT = File.join(File.dirname(__FILE__), "../web")
TARGET_DIR_WEB = "#{TARGET_DIR}/app/web"

def copy_and_replace(src, dest, pattern, replace)
  text = File.read(src) 
  text.gsub!(pattern, replace)
  File.open(dest, "w") { |file| file.write(text) }
end

CLEAN.include(TARGET_DIR)

directory TARGET_DIR
directory TARGET_DIR_WEB

task :init => [:clean, TARGET_DIR]

task :install_server_files => [TARGET_DIR] do |t|
  cp_r "#{SERVER_ROOT}/app", TARGET_DIR
  ["#{SERVER_ROOT}/Gemfile", "#{SERVER_ROOT}/start_server.sh"].each {|f| cp(f, TARGET_DIR)}
  copy_and_replace("#{SERVER_ROOT}/config.ru", "#{TARGET_DIR}/config.ru", /current_environment\s+=\s+'development'/, "current_environment = 'production'")
  mkdir_p "#{TARGET_DIR}/db/production/dashboard"
  mkdir_p "#{TARGET_DIR}/db/production/monitor"
end

task :copy_html_files =>[TARGET_DIR, TARGET_DIR_WEB] do |t|
  cp_r "#{WEB_ROOT}/html", TARGET_DIR_WEB
end
task :copy_img_files => [TARGET_DIR, TARGET_DIR_WEB] do |t|
  cp_r "#{WEB_ROOT}/img", TARGET_DIR_WEB
end
task :copy_css_files => [TARGET_DIR, TARGET_DIR_WEB] do |t|
  mkdir_p "#{TARGET_DIR_WEB}/css"
  cp_r "#{WEB_ROOT}/css/jquery-ui", "#{TARGET_DIR_WEB}/css"
  [
    "#{WEB_ROOT}/css/angular-ui.min.css",
    "#{WEB_ROOT}/css/bootstrap-responsive.min.css",
    "#{WEB_ROOT}/css/bootstrap.min.css",
    "#{WEB_ROOT}/css/bootstrapSwitch.css"
  ].each {|f| cp(f, "#{TARGET_DIR_WEB}/css")}
end
task :copy_lib_files => [TARGET_DIR, TARGET_DIR_WEB] do |t|
  mkdir_p "#{TARGET_DIR_WEB}/lib"
  [
    "#{WEB_ROOT}/lib/underscore-min.js",
    "#{WEB_ROOT}/lib/bootstrap.min.js",
    "#{WEB_ROOT}/lib/bootstrapSwitch.js", 
    "#{WEB_ROOT}/lib/jquery-1.9.1.min.js",
    "#{WEB_ROOT}/lib/jquery.blockUI.js",
    "#{WEB_ROOT}/lib/jquery-ui-1.10.1.custom.min.js",
    "#{WEB_ROOT}/lib/jquery.cycle2.min.js",
    "#{WEB_ROOT}/lib/moment.min.js",
    "#{WEB_ROOT}/lib/angular.min.js",
    "#{WEB_ROOT}/lib/angular-ui.min.js"
  ].each {|f| cp(f, "#{TARGET_DIR_WEB}/lib")}
  mkdir_p "#{TARGET_DIR_WEB}/steal"
  cp("#{WEB_ROOT}/steal/steal.production.js", "#{TARGET_DIR_WEB}/steal/steal.js")
  cp_r("#{WEB_ROOT}/steal/dev", "#{TARGET_DIR_WEB}/steal")
end
task :copy_javascript_files => [TARGET_DIR, TARGET_DIR_WEB] do |t|
  mkdir_p "#{TARGET_DIR_WEB}/jashboard"
  cp "#{WEB_ROOT}/jashboard/environment.js", "#{TARGET_DIR_WEB}/jashboard"
  copy_and_replace("#{WEB_ROOT}/jashboard/loader.js", "#{TARGET_DIR_WEB}/jashboard/loader.js", /var\s+JASHBOARD_ENVIRONMENT\s+=\s+'development';/, "var JASHBOARD_ENVIRONMENT = 'production';")
end
task :package_javascript_files => [TARGET_DIR, TARGET_DIR_WEB, :copy_css_files, :copy_lib_files] do |t|
  system "node #{WEB_ROOT}/package.js #{TARGET_DIR_WEB}"
end
task :copy_web_files => [TARGET_DIR, TARGET_DIR_WEB] do |t|
  cp "#{WEB_ROOT}/index.html", TARGET_DIR_WEB
end

multitask :install_web_files => [:copy_html_files, :copy_img_files, :copy_css_files, :copy_lib_files, :copy_javascript_files, :package_javascript_files, :copy_web_files]

desc "install the application in folder: #{File.join(File.dirname(__FILE__), TARGET_DIR)}"
task :install =>[:init, :install_server_files, :install_web_files]
