source "https://rubygems.org"
gem 'sinatra'
gem 'sinatra-contrib'
gem 'nokogiri'
gem 'fsdb'
gem 'uuidtools'
gem 'ipsum'
gem 'grit'

group :test do
  gem 'rspec'
  gem 'json_spec'
  gem 'cucumber'
end
