source "https://rubygems.org"

gem 'rake'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'fsdb'
gem 'uuidtools'

# plugins dependencies
gem 'nokogiri'
gem 'ipsum'
gem 'rugged'
gem 'go_api_client'

group :test do
  gem 'json', '~> 1.7.7'
  gem 'rspec', '>= 3.0'
  gem 'json_spec'
  gem 'cucumber'
  gem 'qunit-selenium'
  gem 'pry'
  gem 'pry-debugger'
end
