require 'rake'
require 'rspec/core/rake_task'
require 'cucumber/rake/task'

desc "Run specs matching the pattern (or all of them if no pattern specified)"
task :test, [:file_pattern] do |t, args|
  RSpec::Core::RakeTask.new(:pattern_spec) do |task|
    task.rspec_opts = '-c -fd'
    task.verbose = false
    task.pattern = args.file_pattern if args.file_pattern
  end
  Rake::Task[:pattern_spec].invoke
end

Cucumber::Rake::Task.new do |t|
  t.cucumber_opts = %w{--format pretty}
end

desc "Clear all stored data in DEV environment"
task :db_clean do
  FileUtils.rm Dir.glob("db/development/**/*.txt")
  FileUtils.rm Dir.glob("db/development/**/..fsdb.meta.*.txt")
end

