require 'rspec/core/rake_task'
require 'cucumber/rake/task'
require './spec/fsdb_helper'

desc "Run specs matching the pattern (or all of them if no pattern specified)"
task :test, [:file_pattern] do |t, args|
  RSpec::Core::RakeTask.new(:pattern_spec) do |task|
    task.rspec_opts = '-c -fd'
    task.verbose = false
    task.pattern = args.file_pattern if args.file_pattern
  end
  Rake::Task[:pattern_spec].invoke
end

Cucumber::Rake::Task.new do |t|
  t.cucumber_opts = %w{--format pretty --expand --tags ~@wip} 
end

desc "Clear all stored data in a target environment (default: DEV)"
task :db_clean, [:environment] do |t, args|
  environment = args.environment  || "development"
  db_helper = Jashboard::FSDBHelper.new("db/#{environment}")
  db_helper.clean_data
end

desc 'Open FuncUnit tests page with Selenium and run tests'
task :selenium_funcunit, [:test_suite] do |task, args|
  test_suite = args.with_defaults(test_suite: "")[:test_suite]
  suite_param = "?suite=#{test_suite}" unless test_suite.empty?

  sh %Q(qunit-selenium --timeout=300 --screenshot=funcunit.png http://localhost:8001/funcunit.html#{suite_param})
end
